version: '3'
services:
  node:
    build: .
    container_name: naivecoin-node
    restart: always
    ports:
      - "3001:3001"
      - "6001:6001"
    environment:
      - HTTP_PORT=3001
      - P2P_PORT=6001
      # PEERS is now optional (auto-connects to Public Bootnode)
      - PEERS=
      - PRIVATE_KEY=node/wallet/private_key
    volumes:
      # Mount a separate data folder for the peer node to persist the wallet
      - ./node-peer/data:/app/node/wallet
      # Also mount the data folder for possible blockchain DB persistence if needed later
      # - ./node-peer/db:/app/data
